package com.launchly.worker.deploy;

import com.launchly.worker.entities.Project;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

/**
 * When a repository has no root {@code Dockerfile}, generate {@code Dockerfile.launchly}
 * from the project's install / build / start commands so users are not forced to learn Docker first.
 * If the repository already contains {@code Dockerfile}, this class does nothing.
 */
public final class ImplicitDockerfileGenerator {

    public static final String IMPLICIT_DOCKERFILE_NAME = "Dockerfile.launchly";

    private ImplicitDockerfileGenerator() {
    }

    public static boolean hasRootDockerfile(File workDir) {
        File f = new File(workDir, "Dockerfile");
        return f.isFile() && f.length() > 0;
    }

    /**
     * @return {@link #IMPLICIT_DOCKERFILE_NAME} if a new file was written; {@code null} if repo already has Dockerfile
     */
    public static String writeIfMissing(File workDir, Project project) throws IOException {
        if (hasRootDockerfile(workDir)) {
            return null;
        }
        String install = nonBlank(project.getInstallCommand())
                ? project.getInstallCommand().trim()
                : "npm ci";
        String build = nonBlank(project.getBuildCommand())
                ? project.getBuildCommand().trim()
                : "echo \"no build_command configured\"";
        String start = nonBlank(project.getStartCommand())
                ? project.getStartCommand().trim()
                : "npm start";
        int port = project.getDefaultPort() != null ? project.getDefaultPort() : 3000;

        String body = """
                # Generated by Launchly — no Dockerfile in repo root. Uses project install/build/start commands.
                # Add your own Dockerfile to the repository to override this behaviour.
                FROM node:20-bookworm-slim
                WORKDIR /app
                ENV NODE_ENV=production
                COPY . .
                RUN %s
                RUN %s
                EXPOSE %d
                CMD %s
                """.formatted(runShCExec(install), runShCExec(build), port, runShCExec(start));

        File out = new File(workDir, IMPLICIT_DOCKERFILE_NAME);
        Files.writeString(out.toPath(), body.stripLeading(), StandardCharsets.UTF_8);
        return IMPLICIT_DOCKERFILE_NAME;
    }

    /** Dockerfile exec-form: ["sh","-c","..."] with JSON escaping for the inner shell string. */
    static String runShCExec(String shellCommand) {
        String esc = shellCommand
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", " ")
                .replace("\r", "");
        return "[\"sh\", \"-c\", \"" + esc + "\"]";
    }

    private static boolean nonBlank(String s) {
        return s != null && !s.isBlank();
    }
}
