ALTER TABLE environments
  ADD COLUMN IF NOT EXISTS deploy_mode VARCHAR(20) DEFAULT 'local',
  ADD COLUMN IF NOT EXISTS host VARCHAR(255),
  ADD COLUMN IF NOT EXISTS ssh_user VARCHAR(100),
  ADD COLUMN IF NOT EXISTS deploy_dir VARCHAR(500),
  ADD COLUMN IF NOT EXISTS external_port INTEGER,
  ADD COLUMN IF NOT EXISTS data_strategy VARCHAR(50) DEFAULT 'isolated',
  ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT TRUE;
